# Exported from Render on 2024-09-16T09:35:50Z
services:
- type: web
  name: ElectricBillEstimator
  runtime: python
  repo: https://github.com/vgerald/ElectricBillEstimator
  plan: free
  envVars:
  - key: PORT
    sync: false
  region: virginia
  buildCommand: pip install -r requirements.txt
  startCommand: uvicorn main:app --host 0.0.0.0 --port $PORT
version: "1"
